In [80]:
import numpy as np

In [81]:
b = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [9]:
# Get specified element (work outside in)
print(b[0,1,1])
print(b[1,0,1])

4
6


In [13]:
# replace 
b[:,1, :] = [[9,9], [8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

### Initializing different types of arrays

In [20]:
# All 0's Matrix
print(np.zeros(5))
print(np.zeros((2,3)))

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


In [23]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [26]:
# Any other number
np.full((2,2), 99, dtype=float)

array([[99., 99.],
       [99., 99.]])

In [27]:
# Any other number (full like method)
np.full_like(b, 4)

array([[[4, 4],
        [4, 4]],

       [[4, 4],
        [4, 4]]])

In [28]:
# Random decimal number
np.random.rand(4,2)

array([[0.12823186, 0.42219685],
       [0.16488078, 0.14147483],
       [0.44855571, 0.00132118],
       [0.52279288, 0.22732873]])

In [30]:
 # Random sample method
 np.random.random_sample(b.shape)

array([[[0.05789017, 0.25091865],
        [0.18676238, 0.96264869]],

       [[0.64603969, 0.93139275],
        [0.56489343, 0.24764133]]])

In [33]:
# Random integer values
np.random.randint(-4,8, size=(3,3))

array([[ 5, -3,  4],
       [-1,  5, -4],
       [ 4, -4,  4]])

In [36]:
# Identitiy matrix
np.identity(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [40]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [48]:
output = np.ones((5,5))
#print(output)

z = np.zeros((3,3))
z[1,1] = 9
#print(z)

output[1:4, 1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Mathematics

In [51]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [53]:
print(a + 2)
print(a - 2)
print(a * 2)
print(a / 2)

[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]


In [54]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [55]:
a ** 2

array([ 1,  4,  9, 16])

In [57]:
# Take the sin
print(np.sin(a))
print(np.cos(a))

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


#### Linear Algebra

In [59]:
a = np.ones([2,3])
print(a)

b = np.full((3,2), 2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [60]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [61]:
# Finding determinant
c = np.identity(3)
np.linalg.det(c)

1.0

#### Statistics

In [63]:
stats = np.array([[1,2,3], [4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [67]:
print(np.min(stats))
print(np.min(stats, axis=0))

1
[1 2 3]


In [65]:
np.max(stats)

6

In [69]:
np.sum(stats, axis=0)

array([5, 7, 9])

### Reorganizing arrays

In [72]:
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before)

after = before.reshape((8,1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [74]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1, v2, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [76]:
# Horizontal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack([h1,h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])